### ISSUE TITLE
In REPL, redefine the defined variables. If the values are different, the program will crash

### ISSUE THREAD

**Issue by C-BJ** [erg-lang/erg#72] opened 2022-08-21 05:38 UTC
![image](https://user-images.githubusercontent.com/62678643/185777204-dfd71002-80f3-4818-9703-982b529adfcd.png)

**Comment by mtshiba** [comment] 2022-08-21 08:06
Erg prohibits reassignment of variables, but its error handling does not seem to be working well.

**Comment by C-BJ** [comment] 2022-08-21 08:13
> Erg prohibits reassignment of variables, but its error handling does not seem to be working well.

If the reassigned value is the same, it will report an error instead of a crash

**Comment by mtshiba** [comment] 2022-08-21 08:20
Even if the resulting substituted values are the same, an error is still generated.

if this is OK,

```python
i = 1
i = 1
```

```python
rand = pyimport "random"
i = 1

i = rand.randint!(0, 1)
```

There is a one in two chance that this code must be valid. That is nonsense.

Nevertheless, this code should be failed with errors normally without crashing.

**Comment by C-BJ** [comment] 2022-08-21 08:39
> Even if the resulting substituted values are the same, an error is still generated.
> 
> if this is OK,
> 
> ```python
> i = 1
> i = 1
> ```
> 
> ```python
> rand = pyimport "random"
> i = 1
> 
> i = rand.randint!(0, 1)
> ```
> 
> There is a one in two chance that this code must be valid. That is nonsense.
> 
> That said, this code should be failed with errors normally without crashing.

Yes, I'm describing the error

**Comment by mtshiba** [comment] 2022-08-21 08:54
Yes, I will fix this unintended behavior soon.

**Closed** 2022-09-11 14:20 UTC
Labels: bug, compiler-bug, inference-bug, seems-medium
